//+build windows
package test_wasmtime // generated by wasmtimegen

import "core:testing"
import wt ".."

@(test)
verify_type_sizes :: proc(t: ^testing.T) {
	expect_size(t, wt.size_t, 8)
	expect_size(t, wt.wasm_byte_vec_t, 16)
	expect_size(t, wt.wasm_limits_t, 8)
	expect_size(t, wt.wasm_valtype_vec_t, 16)
	expect_size(t, wt.wasm_functype_vec_t, 16)
	expect_size(t, wt.wasm_globaltype_vec_t, 16)
	expect_size(t, wt.wasm_tabletype_vec_t, 16)
	expect_size(t, wt.wasm_memorytype_vec_t, 16)
	expect_size(t, wt.wasm_externtype_vec_t, 16)
	expect_size(t, wt.wasm_importtype_vec_t, 16)
	expect_size(t, wt.wasm_exporttype_vec_t, 16)
	expect_size(t, wt.wasm_val_t, 16)
	expect_size(t, wt.wasm_val_vec_t, 16)
	expect_size(t, wt.wasm_frame_vec_t, 16)
	expect_size(t, wt.wasm_extern_vec_t, 16)
	expect_size(t, wt.wasmtime_linear_memory_t, 32)
	expect_size(t, wt.wasmtime_memory_creator_t, 24)
	expect_size(t, wt.wasmtime_func_t, 16)
	expect_size(t, wt.wasmtime_table_t, 16)
	expect_size(t, wt.wasmtime_memory_t, 16)
	expect_size(t, wt.wasmtime_global_t, 16)
	expect_size(t, wt.wasmtime_extern_t, 24)
	expect_size(t, wt.wasmtime_val_t, 24)
	expect_size(t, wt.wasmtime_instance_t, 16)
	expect_size(t, wt.wasmtime_guestprofiler_modules_t, 16)
	expect_size(t, wt.wasmtime_async_continuation_t, 24)
	expect_size(t, wt.wasmtime_stack_memory_t, 24)
	expect_size(t, wt.wasmtime_stack_creator_t, 24)
	expect_size(t, wt.wasmtime_extern_union_t, 16)
	expect_size(t, wt.wasmtime_valunion_t, 16)
	expect_size(t, wt.wasmtime_val_raw_t, 16)
	expect_value(t, wt.stdin, 0x00000000)
	expect_value(t, wt.stdout, 0x00000001)
	expect_value(t, wt.stderr, 0x00000002)
}
